import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import "@styles/globals.css";
import "@styles/style.css";
import BackToTop from "@/components/BackToTop";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css"
        />
      </head>
      <body>
        <BackToTop />
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
