import Navbar from "@components/Navbar";
import Footer from "@components/Footer";
import "@styles/globals.css";
import "@styles/style.css";
import BackToTop from "@/components/BackToTop";
import MobileNav from "@/components/MobileNav";

export const metadata = {
  title: "Devstella - Pioneering Next-Gen Software Solutions",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/iconoir-icons/iconoir@main/css/iconoir.css"
        />
      </head>
      <body>
        <BackToTop />
        {/* Desktop Navbar: Visible only on large screens */}
        <div className="hidden md:block">
          <Navbar />
        </div>

        {/* Mobile Navigation: Visible only on medium and smaller screens */}
        <div className="md:hidden">
          <MobileNav />
        </div>
        {children}
        <Footer />
      </body>
    </html>
  );
}
